Repository ASS-G/Batch-1-Assignments, pull requests merged in 2019-10, with the labels that each got.

#2 SREE VISHAL R CS-C 2nd yr
  Assignment 1/180501143/hello_world.py
Labels: Submission

#3 Krishnan S CS B ROLL NO 80
  .gitconfig
  Assignment 1/180501080/helloworld.py
Labels: Submission

#6 SURAJRAM S 2 nd YR CSE C ROLL NO 154
  Assignment 1/180501154/helloworld.py
Labels: Batch 1, Submission

#10 Kamalishree A- 2nd yr-CSE -B-180501068
  Assignment 1/180501068/HelloWorld.py
Labels: Batch 1, Submission

#12 Harshini.R.S Cs A 180501055
  Assignment 1/180501055/hello_world.py
Labels: Batch 1, Submission

#31 Yuvaraj J: CS C 180501200
  Assignment 1/180501200/hello_world.py
Labels: Board

#13 Nivetha K S: CS B 180501104
  Assignment 1/180501104/hello.py
Labels: Batch 1, Submission

#32 Abhinesh CSE-A 2ND YEAR 180501003
  Assignment 1/180501003/helloworld.py
Labels: Batch 1, Submission

#29 Priya Shrinithi R 2nd year CSE-B 180501113
  Assignment 1/180501113/HelloWorld.py
Labels: Batch 1, Submission

#35 Swetha.S: CS C 180501157
  Assignment 1/180501157/hello_world.py
Labels: Batch 1, Submission

#27 V.Srivatsan CS-C 180501147
  Assignment 1/180501147/helloworld.py
Labels: Batch 1, Submission

#25 Karthiga.R 2nd year CSE - B 180501069
  Assignment 1/180501069/hello_world.py
Labels: Batch 1, Submission

#38 KUMARAN TR:CS B 180501081
  Assignment 1/180501081/hello_world.py
Labels: Batch 1, Submission

#39 b.HARIKISHORE CSE-A 2ND YEAR 180501052
  Assignment 1/180501052/helloworld.py
Labels: Batch 1, Submission

#30 benito thomas CSE-A 2ND YEAR 180501024
  Assignment1/180501024/helloworld.py
Labels: Batch 1, Submission

#24 Mohanakrishna Gopika V - 2nd Year CSE B 180501092
  180501092/test.py
Labels: Batch 1, Submission

#20 Dhivyadharshini.N ,CS-A,180501040
  Assignment 1/180501040/hello world.py
Labels: Batch 1, Submission

#23 R Barathkumar - 2nd Year CSE-A 180501022
  Assignment 1/180501022/helloworld.py
Labels: Batch 1, Submission

#19 Madhan Kumar CS B 180501088
  Assignment 1/180501088/hello_world.py
Labels: Batch 1, Submission

#40 Pradeep S: CS B 180501107
  Assignment 1/180501107/hello_world.py
Labels: Batch 1, Submission

#14 Kirthana S - 2nd Year CSE-B 180501078
  Assignment 1/180501078/hello_world.py
Labels: Batch 1, Submission

#17 Dhivya.C 2nd year Cse-A 180501039
  Assignment 1/180501039/hello_world.py
Labels: Batch 1, Submission

#7 Esakki.E 2nd year CSE-A 180501043
  Assignment 1/180501043/hello.py
Labels: Batch 1, Submission

#41 K.KEERTHANA: CS B 180501075
  Assignment 1/180501075/helloworld.py
Labels: Batch 1, Submission

#46 Hariharan S - 2nd Year CSE-A 180501051
  Assignment 1/180501051/hello.py
Labels: Batch 1, Submission

#44 Chandru - 2nd Year CSE A 180501028
  Assignment 1/180501028/helloworld.py
Labels: Batch 1, Submission

#47 Shruti S - 2nd Year CSE C 180501138
  Assignment 1/180501138/helloworld.py
Labels: Batch 1, Submission

#57 SRUTHI S CS C 180501150
  Assignment 1/180501150/hello_world.py
Labels: Batch 1, Submission

#58 HARISHRAJ CSE-A 2ND YEAR 180501054
  Assignment 1/180501054/helloworld.py
Labels: Batch 1, Submission

#56 Hemavarshini L - 2nd Year CSE A 180501058
  Assignment 1/180501058/helloworld.py
Labels: Batch 1, Submission

#54 G Balakumaran - 2nd Year CSE A 180501021
  Assignment 1/180501021/helloworld.py
Labels: Batch 1, Submission

#53 Devprasath - 2nd Year CSE A 180501036
  Assignment 1/180501036/helloworld.py
Labels: Batch 1, Submission

#50 Daicy Rani P - 2nd Year CSE A 180501031
  Assignment 1/180501031/hello.py
Labels: Batch 1, Submission

#61 Seshai Hari 2nd year CS-C 180501135
  Assignment 1/180501135/.hello_world.py.swp
  Assignment 1/180501135/hello_world.py
Labels: Batch 1, Submission

#52 Vishwesh M - 2nd Year CSE C 180501179
  Assignment 1/180501179/hello-world.py
Labels: Batch 1, Submission

#60 Athishree V - 2nd Year CSE A 180501018
  Assignment 1/180501018/hello.py
Labels: Batch 1, Submission

#62 Iswariya M- 2nd Year CSE A 180501062
  Assignment 1/180501062/Hello World.py
Labels: Batch 1, Submission

#63 Praveen T P - 2nd Year CSE B 180501111
  Assignment 1/180501111/helloworld.py
Labels: Batch 1, Submission

#55 Kunchay Sree Meghana - 2nd Year CSE B 180501082
  helloworld.py
Labels: Batch 1, Submission

#69 Vishnupriyavelmurugan - 2nd Year CSE C 180501178
  Assignment 1/180501178/hello_world.py
Labels: Batch 1, Submission

#68 Vishali - 2nd Year CSE C 180501176
  Assignment 1/180501176/hello.py
Labels: Batch 1, Submission

#67 Ilakkiya K - 2nd Year CSE A 180501060
  Assignment 1/180501060/helloworld.py
Labels: Batch 1, Submission

#65 Smrithi S - 2nd Year CSE C 180501141
  Assignment 1/180501141/index.html
  Assignment 1/180501141/style.css
Labels: Batch 1, Submission

#18 Vishnupriyavelmurugan - 2nd Year CSE C 180501178
  Assignment 1/180501178/hello_world.py
Labels: Batch 1, Submission

#51 Vaishnavi S - 2nd Year CSE C 180501166
  Assignment 1/180501166/Hello_World.py
Labels: Batch 1, Submission

#71 Bharath Vyas S - 2nd Year CSE A 180501025
  Assignment 1/180501025/hello_world.py
Labels: Batch 1, Submission

#70 Bhargav Reddy V- 2nd Year CSE A 180501026
  Assignment 1/180501026/hello_world.py
Labels: Batch 1, Submission

#73 shirisha o 2nd year CS C 180501136
  Assignment 1/180501136/hello_world.py
Labels: Batch 1, Submission

#72 Deva Dharshini G - 2nd Year CSE A 180501035
  Assignment 1/180501035/deva.py
Labels: Batch 1, Submission

#78 Yumesh55-2nd Year cs c 180501185
  Assignment 1/180501185/hello_world.py
Labels: Batch 1, Submission

#79 Harshitha Y-2nd Year Cse C 180501182
  Assignment 1/180501182/hello_world.py
Labels: Batch 1, Submission

#86 Visali Alagappan-2nd Year Cse c 180501173
  Assignment 1/180501173/helloworld.py
Labels: Batch 1, Submission

#87 Mahesh-2nd Year Cse c 180501180
  180501180
  Assignment 1/180501180/hello_world.py
Labels: Batch 1, Submission

#66 Monnishaa N M - 2nd Year CSE B 180501094
  Assignment 1/180501094/hello_world.py
Labels: Batch 1, Submission

#75 Sruthi KJ - 2nd Year CSE C 180501149
  Assignment 1/180501149/HelloWorld.py
Labels: Batch 1, Submission

#90 Deleted unwanted files and moved files
  Assignment 1/180501181/hello_world.py
  Assignment1/180501181/.hello_world.swp
Labels: Board

#95 Prathul - 2nd Year CSE B 180501109
  Assignment 1/180501109/hello.py
Labels: Batch 1, Submission

#97 Add new Assignment
  README.md
Labels: Board

#102 Nandhakumar - 2nd year CS B 180501097
  Assignment 2/180501097/attendanceStudents.py
  Assignment 2/180501097/occurances.py
  Assignment 2/180501097/robberThief.py
Labels: Batch 1, Submission

#105 Surajram S - 2nd Year CSE C 180501154
  Assignment 2/180501154/attendanceStudents.py
  Assignment 2/180501154/occurances.py
  Assignment 2/180501154/robberThief.py
Labels: Batch 1, Submission

#106 KJ Sruthi - 2nd Year CSE C 180501149
  Assignment 2/180501149/attendanceStudents.py
  Assignment 2/180501149/occurences.py
  Assignment 2/180501149/robberThief.py
Labels: Batch 1, Submission

#104 Kamalishree - 2nd Year CSE B 180501068
  Assignment 2/KAMALISHREE - 2nd yr CSE B 180501068/occurances.py
  Assignment 2/KAMALISHREE - 2nd yr CSE B 180501068/robber.py
  Assignment 2/KAMALISHREE - 2nd yr CSE B 180501068/student-attendance.py
Labels: Batch 1, Submission

#98 Krishnan S - 2nd Year CSE B 180501080
  Assignment 2/180501080/attendanceStudents.py
  Assignment 2/180501080/occurances.py
  Assignment 2/180501080/robberThief.py
Labels: Batch 1, Submission

#123 Palaniappan S - 2nd Year CSE B 180501105
  Assignment 2/180501105/attendanceStudents.py
  Assignment 2/180501105/occurences.py
  Assignment 2/180501105/robberThief.py
Labels: Batch 1, Submission

#142 Benito Thomas T - 2nd Year CSE A 180501024
  Assignment 2/180501024/attendanceStudents.py
  Assignment 2/180501024/occurances.py
  Assignment 2/180501024/robberthief.py
Labels: Batch 1, Submission

#152 Lakshman Kumar D - 2nd Year CSE B 180501084
  Assignment 2/180501084/attendanceStudents.py
  Assignment 2/180501084/occurences.py
  Assignment 2/180501084/robberThief.py
Labels: Batch 1, Submission

#111 Athishree V - 2nd Year CSE A 180501018
  Assignment 2/180501018/attendanceStudents.py
  Assignment 2/180501018/occurances.py
  Assignment 2/180501018/robberThief.py
Labels: Batch 1, Submission

#138 Chandru R - 2nd Year CSE A 180501028
  Assignment 2/180501028/attendanceStudents.py
  Assignment 2/180501028/occurances.py
  Assignment 2/180501028/robberthief.py
Labels: Batch 1, Submission

#132 Abhinesh R P - 2nd Year CSE A 180501003
  Assignment 2/180501003/attendanceStudents.py
  Assignment 2/180501003/occurances.py
  Assignment 2/180501003/robberthief.py
Labels: Batch 1, Submission

#129 Bharath Vyas S - 2nd Year CSE A 180501025
  Assignment 2/180501025/attendanceStudent.py
  Assignment 2/180501025/occurances.py
  Assignment 2/180501025/robberThief.py
Labels: Batch 1, Submission

#137 Balakumaran G - 2nd Year CSE A 180501021
  Assignment 2/180501021/attendanceStudents.py
  Assignment 2/180501021/occurances.py
  Assignment 2/180501021/robberthief.py
Labels: Batch 1, Submission

#128 Ashok J - 2nd Year CSE A 180501015
  Assignment 2/180501015/attendanceStudents.py
  Assignment 2/180501015/occurances.py
  Assignment 2/180501015/robberthief.py
Labels: Batch 1, Submission

#120 Daicy Rani P - 2nd Year CSE A 180501031
  Assignment 2/180501031/attendanceStudents.py
  Assignment 2/180501031/occurances.py
  Assignment 2/180501031/robberThief.py
Labels: Batch 1, Submission

#124 Barathkumar R - 2nd Year CSE A 180501022
  Assignment 2/180501022/attendanceStudents.py
  Assignment 2/180501022/occurances.py
  Assignment 2/180501022/robberthief.py
Labels: Batch 1, Submission

#146 Mohamed Hassan J - 2nd Year CSE B 180501091
  Assignment 2/180501091/attendancestudents.py
  Assignment 2/180501091/occurances.py
  Assignment 2/180501091/robbertheif.py
Labels: Batch 1, Submission

#147 Nivetha K S -2nd year CSE B 180501104
  Assignment 2/180501104/attendanceStudents.py
  Assignment 2/180501104/occurances.py
  Assignment 2/180501104/robberThief.py
Labels: Batch 1, Submission

#117 Madhan Kumar M - 2nd Year CSE B 180501088
  Assignment 2/180501088/attendanceStudents.py
  Assignment 2/180501088/occurances.py
  Assignment 2/180501088/robberThief.py
Labels: Batch 1, Submission

#156 Arivanand R N - 2nd Year CSE A 180501013
  Assignment 2/180501013/attendanceStudents.py
  Assignment 2/180501013/occurances.py
  Assignment 2/180501013/robberthief.py
Labels: Batch 1, Submission

#158 Rithania R - 2nd Year CSE B 180501119
  Assignment 2/180501119/attendancestudents.py
  Assignment 2/180501119/occurances.py
  Assignment 2/180501119/robbertheif.py
Labels: Batch 1, Submission

#154 Visali Alagappan - 2nd Year CSE C 180501173
  Assignment 2/180501173/Occurrances.py
  Assignment 2/180501173/attendanceStudent.py
  Assignment 2/180501173/robberThief.py
Labels: Batch 1, Submission

#145 Vulchi Mahesh Babu - 2nd Year CSE C 180501180
  Assignment 2/180501180/input.py
  Assignment 2/180501180/robin.py
  Assignment 2/180501180/stringocc.py
Labels: Batch 1, Submission

#121 Vaishnavi J - 2nd Year CSE C 180501165
  Assignment2/180501165/attendanceStudent.py
  Assignment2/180501165/occurances.py
  Assignment2/180501165/robberThief.py
Labels: Batch 1, Submission

#125 Pradeep S - 2nd Year CSE B 180501107
  Assignment 2/180501107/attendanceStudents.py
  Assignment 2/180501107/occurences.py
  Assignment 2/180501107/robberThief.py
Labels: Batch 1, Submission

#110 Swatika Ayyappan - 2nd year CSE C 180501155
  Assignment 2/180501155/occurances.py
  Assignment 2/180501155/robberThief.py
  Assignment 2/180501155/studentAttendance.py
Labels: Batch 1, Submission

#140 Smrithi S - 2nd Year CSE C 180501141
  Assignment 2/180501141/Occurrences.py
  Assignment 2/180501141/attendanceStudents.py
  Assignment 2/180501141/robberThief.py
Labels: Batch 1, Submission

#136 Sinthana R - 2nd Year CSE C 180501140
  Assignment2/180501140/attendancestudent.py
  Assignment2/180501140/occurances.py
  Assignment2/180501140/robbertheif.py
Labels: Batch 1, Submission

#173 Sruthi S - 2nd Year CSE C 180501150
  Assignment 2/180501150/occurences.py
Labels: Batch 1, Submission

#99 Sree Vishal R - 2nd year CSE C 180501143
  Assignment 2/18050143/attendanceStudents.py
  Assignment 2/18050143/occurances.py
  Assignment 2/18050143/robberThief.py
Labels: Batch 1, Submission

#141 Karthiga R - 2nd Year CSE B 180501069
  Assignment 2/180501069/Occurances.py
  Assignment 2/180501069/attendanceStudents.py
  Assignment 2/180501069/robberThief.py
Labels: Batch 1, Submission

#170 Uma - 2nd Year CSE C 180501164
  Assignment 2/180501164/attendanceStudents.py
  Assignment 2/180501164/occurances.py
  Assignment 2/180501164/robberThief.py
Labels: Batch 1, Submission

#160 Srivatsan V - 2nd Year CSE C 180501147
  Assignment 2/180501147/attendanceStudents.py
  Assignment 2/180501147/occurences.py
  Assignment 2/180501147/robberThief.py
Labels: Batch 1, Submission

#181 Niranjani K P - 2nd Year CSE B 180501103
  Assignment 2/180501103/attendanceStudents.py
  Assignment 2/180501103/occurances.py
  Assignment 2/180501103/robberThief.py
Labels: Batch 1, Submission

#163 Tejkiran - 2nd Year CSE C 180501161
  Assignment 2/attstud.py
  Assignments2/occurences.py
  Assignments2/thief.py
Labels: Batch 1, Submission

#144 Prithvi Raj M V - 2nd Year CSE C 180501167
  Assignment 2/180501167/attendanceStudents.py
  Assignment 2/180501167/occurances.py
  Assignment 2/180501167/robberThief.py
Labels: Batch 1, Submission

#175 Vijay Natraj K - 2nd Year CSE C 180501170
  Assignment 1/180501170/hello_world.py
  Assignment 2/180501170/attedanceStudent.py
  Assignment 2/180501170/occurances.py
  Assignment 2/180501170/robberThief.py
Labels: Batch 1, Submission
